### ISSUE TITLE
Add support for mouse events

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/diku-canvas#22]
Adding support for mouse events does not seem too complicated and would greatly increase the possibilities for "reactive programming" - one of the things we "lost" when WinForms-support was removed from Mono. 

The SDL_MouseButtonEvent looks a lot like the key-event (at least complexity-wise). 
 
https://wiki.libsdl.org/SDL_MouseButtonEvent 

// Edit
Having looked a bit into it, "not too complicated" is an understatement. 

Currently we define the SDL_KeyboardEvent struct, and assume all events are keyboard-events (or that we **only** need the event type). 
To handle SDL_MouseButtonEvent as well, (I think) we need to implement support for SDL_Event, a union of event-structs. 
Since the SDL_KeyboardEvent and SDL_MouseButtonEvent structs have overlapping fields, they are hard to convert to managed code. I am not experienced enough with PInvoke/Interop-stuff to see a good solution to this. 

I guess it might be possible to marshall all events into a byte array of fixed size and construct the managed objects we need manually.

**Comment by kfl** [comment]
Done via PR #25
