### ISSUE TITLE
Fix bundling of SDL2_image

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/diku-canvas#8]
Currently saving a canvas to png works in these cases:
- Windows
- Linux/Mac, *if* the user has SDL2.{so,dylib} in the search path(s) used by `ld`/`dyld`.

`SDL2_image` attempts to load `SDL2` but can not find the bundled `SDL2.{so,dylib}`. 

My best proposed fix, which will also solve other problems (and bring more, yay!):

**New problems**:  
- We have to build SDL2_image ourselves, for at least 3 platforms  
**New benefits:**  
- We can remove all the unneeded dependencies such as jxl-support  

**Mac**
1. `Build` a custom `SDL2_image.dylib` either as a fat lib or as two separate libs for x64 and arm64. 
2. Either:
    2a. Use `install_name_tool` to edit RPATH of the library.
    2b. Give up on life, learn CMAKE and set the RPATH correctly when building the library.
   
**Linux**
1. Build a custom `SDL2_image.so`.
2. Use e.g. `patchelf` to change the RPATH.

**Comment by kfl** [comment]
I wonder if it might be easier to use [ImageSharp](https://sixlabors.com/products/imagesharp/) or [SkiaSharp](https://github.com/mono/SkiaSharp) instead, rather than using SDL2_image.

**Comment by madsobitsoe** [comment]
I think it might. I looked into a lot of libraries including those when we
were using mono, and back then NuGet-packages were just a
cumbersome process.

Now, with .NET6.0 it might be a different story altogether.

**Comment by madsobitsoe** [comment]
Closing this as we no longer need SDL2_image
